# .github/workflows/ios-review.yml
#
# Example GitHub Actions workflow for running ios-app-review-plugin
# on every push and pull request. Copy this file to your repository's
# .github/workflows/ directory.

name: iOS App Review

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    name: App Store Review Check
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Option A: Use the composite action (if ios-app-review-plugin is the source repo)
      # - name: Run iOS App Review
      #   uses: ahmetsina/ios-app-review-plugin/.github/actions/ios-review@main
      #   with:
      #     project-path: .
      #     format: json
      #     analyzers: all

      # Option B: Install and run manually (works for any repository)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install ios-app-review-plugin
        run: npm install -g ios-app-review-plugin

      - name: Run iOS App Review scan
        id: review
        run: |
          set +e
          ios-app-review scan . \
            --format json \
            --output review-report.json
          EXIT_CODE=$?
          set -e

          echo "exit-code=${EXIT_CODE}" >> "$GITHUB_OUTPUT"

          # Set job outcome based on exit code
          if [ "$EXIT_CODE" -eq 0 ]; then
            echo "::notice::iOS App Review: All checks passed."
          elif [ "$EXIT_CODE" -eq 1 ]; then
            echo "::warning::iOS App Review: Issues detected. See report."
          else
            echo "::error::iOS App Review: Scan failed."
            exit "$EXIT_CODE"
          fi

      - name: Upload review report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-review-report
          path: review-report.json
          retention-days: 30

      - name: Comment on PR with results
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            let body = '## iOS App Review Results\n\n';

            try {
              const report = JSON.parse(fs.readFileSync('review-report.json', 'utf8'));
              const summary = report.summary;

              const statusEmoji = summary.passed ? ':white_check_mark:' : ':x:';
              body += `**Status:** ${statusEmoji} ${summary.passed ? 'Passed' : 'Failed'}\n\n`;
              body += `| Metric | Count |\n|--------|-------|\n`;
              body += `| Errors | ${summary.errors} |\n`;
              body += `| Warnings | ${summary.warnings} |\n`;
              body += `| Info | ${summary.info} |\n`;
              body += `| Total | ${summary.totalIssues} |\n\n`;

              if (summary.errors > 0) {
                body += '### Errors\n\n';
                for (const result of report.results) {
                  for (const issue of result.issues) {
                    if (issue.severity === 'error') {
                      const location = issue.filePath ? ` (\`${issue.filePath}:${issue.lineNumber || ''}\`)` : '';
                      body += `- **${issue.title}**${location}\n  ${issue.description}\n`;
                      if (issue.suggestion) {
                        body += `  > Suggestion: ${issue.suggestion}\n`;
                      }
                      body += '\n';
                    }
                  }
                }
              }
            } catch (e) {
              body += `Could not parse review report: ${e.message}\n`;
            }

            body += '\n---\n*Generated by [ios-app-review-plugin](https://github.com/ahmetsina/ios-app-review-plugin)*';

            // Find existing comment to update
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            const botComment = comments.find(c =>
              c.body.includes('## iOS App Review Results')
            );

            if (botComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: botComment.id,
                body,
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body,
              });
            }

      - name: Fail if issues found
        if: steps.review.outputs.exit-code == '1'
        run: |
          echo "iOS App Review found issues. Review the report artifact for details."
          exit 1
